package com.agent.domain.model;

import java.time.Instant;
import java.util.Map;

/**
 * Represents a response generated by an agent.
 */
public class AgentResponse {
    private String content;
    private ResponseType type;
    private Map<String, Object> metadata;
    private Instant timestamp;
    private TokenUsage tokenUsage;
    
    public AgentResponse() {
        this.timestamp = Instant.now();
    }
    
    public AgentResponse(String content, ResponseType type) {
        this();
        this.content = content;
        this.type = type;
    }
    
    // Getters and setters
    public String getContent() { return content; }
    public void setContent(String content) { this.content = content; }
    
    public ResponseType getType() { return type; }
    public void setType(ResponseType type) { this.type = type; }
    
    public Map<String, Object> getMetadata() { return metadata; }
    public void setMetadata(Map<String, Object> metadata) { this.metadata = metadata; }
    
    public Instant getTimestamp() { return timestamp; }
    public void setTimestamp(Instant timestamp) { this.timestamp = timestamp; }
    
    public TokenUsage getTokenUsage() { return tokenUsage; }
    public void setTokenUsage(TokenUsage tokenUsage) { this.tokenUsage = tokenUsage; }
    
    public enum ResponseType {
        TEXT, TOOL_CALL, ERROR, THINKING
    }
}